### ISSUE TITLE
Can't give names to instrumentation boards in environment

### ISSUE THREAD

**Issue by smartel99** [smartel99/Frasy#3] opened 2024-06-06 18:28 UTC
Giving a name to an instrumentation board in the environment file results in an error in the Generation step:

In environment file:
```lua
local pio = Ib.Add(Ibs.pio, "PIO"):NodeId(2)
```

![image](https://github.com/smartel99/Frasy/assets/36042950/f59e710b-ece4-46f6-9f76-f1a49d662a53)

**Comment by DoubleNom** [comment] 2024-06-06 19:52
Cannot reproduced,
Supposed to be already fixed by commit b78cfec1a9e57ae625b26a8b11b1bb1425eb0c13

Could you check again?

**Comment by DoubleNom** [comment] 2024-06-06 19:55
User was not calling board from script with said name, closing issue

**Closed by DoubleNom** 2024-06-06 19:55 UTC
Labels: bug
